service: questions-aws-stack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    QUESTIONS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-questions
    AWS_DEPLOY_REGION: ${self:provider.region}
    S3_AUDIO_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-questions-audio
    S3_IMAGE_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-questions-images

# exclude tests from package
package:
  exclude:
    - tests/**

functions:
  createQuestion:
    handler: handler/questionsService.create
    events:
      - http:
          method: POST
          path: /questions
          integration: lambda
          cors: true
          request:
            passThrough: NEVER
          response:
            headers:
              Content-Type: "'application/json'"
    environment:
      TRANSLATE_TOPIC: !Ref TranslateTopic
      AUDIO_TOPIC: !Ref AudioConvertTopic
      S3_IMAGE_BUCKET: ${self:provider.environment.S3_IMAGE_BUCKET}
      S3_AUDIO_BUCKET: ${self:provider.environment.S3_AUDIO_BUCKET}
  getQuestion:
    handler: handler/questionsService.get
    events:
      - http:
          method: GET
          path: /questions
          integration: lambda
          cors: true
          request:
            passThrough: WHEN_NO_MATCH
            parameters:
              querystrings:
                id: true
                lang: true
                questionGroup: true
                questionLevel: true
            template:
              application/json: '{
                        "id" : "$input.params(''id'')",
                        "lang" : "$input.params(''lang'')",
                        "questionGroup" : "$input.params(''questionGroup'')",
                        "questionLevel" : "$input.params(''questionLevel'')"
              }'
          response:
            headers:
              Content-Type: "'application/json'"
  translateQuestion:
    handler: handler/questionsService.translate
    events:
      - sns:
          arn: !Ref TranslateTopic
          topicName: TranslateTopic
    environment:
      S3_IMAGE_BUCKET: ${self:provider.environment.S3_IMAGE_BUCKET}
      S3_AUDIO_BUCKET: ${self:provider.environment.S3_AUDIO_BUCKET}
      AUDIO_TOPIC: !Ref AudioConvertTopic
  convertQuestionToAudio:
    handler: handler/questionsService.convertToAudio
    events:
      - sns:
          arn: !Ref AudioConvertTopic
          topicName: AudioConvertTopic
    environment:
      S3_AUDIO_BUCKET: ${self:provider.environment.S3_AUDIO_BUCKET}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
      GatewayResponseDefault5XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseType: DEFAULT_5XX
          RestApiId:
            Ref: 'ApiGatewayRestApi'
    QuestionsDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.QUESTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: lang
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: lang
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: LangGroupIndex
            KeySchema:
              - AttributeName: lang
                KeyType: HASH
              - AttributeName: group
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    TranslateTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TranslateTopic
        DisplayName: TranslateTopic
        Tags:
          - Key: Description
            Value: Handle messages describing text, initial and target lang to translate. Initial lang is not populated to the topic
    AudioConvertTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AudioConvertTopic
        DisplayName: AudioConvertTopic
        Tags:
          - Key: Description
            Value: Handle messages with already translated text to convert to MP3